Repository GCCempt/GCC_OpenSong_bot, pull requests merged in 2021-05, with the labels that each got.

#33 Fixed passage lookup and ftp
  Dockerfile
  myroutine.py
  opensong.py
  passagelookup.py
  sftp_files.py
Labels: bug

#36 Replaces unrecognized command message with a discord embed.
  mydiscord.py
Labels: Improvement

#37 Fixed outstanding bugs
  mydiscord.py
  myroutine.py
  readworshipschedule.py
Labels: bug

#38 fixed line 261 in mydiscord.py
  mydiscord.py
Labels: bug

#39 Added test script; added try/except logic
  mydiscord.py
  myroutine.py
  test_script.py
Labels: enhancement

#47 added validation script during startup
  rundiscord.py
Labels: enhancement

#61 Quick fix for song parsing from worship schedule
  utils.py
Labels: bug

#66 Merge song error hotfix into dev
  utils.py
Labels: bug

#67 fixed error in status display
  monitorfiles.py
Labels: bug

#70 replaced $ to /
  mydiscord.py
Labels: good first issue

#72 Fixed linebreaks in scriptures with hyphen
  addnode.py
  find_dash_number.py
  passagelookup.py
  stringsplit.py
Labels: bug

#76 Song search and validation improvement
  maintainsong.py
  mydiscord.py
  myroutine.py
  opensong.py
  readworshipschedule.py
  test_script.py
  utils.py
Labels: enhancement

#80 Fixes song parsing logic
  utils.py
Labels: bug

#97 hotfix generate_set_name for broken /status command
  monitorfiles.py
Labels: bug

#102 Issue#91 scheduled file cleanup
  getdatetime.py
  monitorfiles.py
  rundiscord.py
  schedule_tasks.py
Labels: enhancement

#118 Dev
  monitorfiles.py
  my_test_routine.py
  mydiscord.py
  pull-sampleset-list.txt
  startup_validation.py
  utils.py
Labels: bug
